CC = clang++
SRC_FILES = lock_free_queue.cpp
OBJ_NAME = lock_free_queue.exe
COMPILER_FLAGS = -std=c++20 -Wall -O0 -g

all:
	$(CC) $(COMPILER_FLAGS) $(SRC_FILES) -o $(OBJ_NAME)
clean:
	rm f ${OBJ_NAME}